name: Linux Arm64 Build with Gradle 

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
  JKUBE_REPOSITORY: https://github.com/rohankanojia/jkube.git
  JKUBE_REVISION: pr/buildpacks-build-strategy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Linux Build With Gradle 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Clone JKube
        run: |
          rm -rf jkube \
          && git clone "$JKUBE_REPOSITORY" --branch "$JKUBE_REVISION" jkube
      - name: Install JKube
        run: mvn ${MAVEN_ARGS} -f "jkube/pom.xml" clean install -DskipTests -Djacoco.skip=true
      - name: Run Integration tests
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          dockerRunArgs: --volume /home/runner/.m2:/home/runner/.m2:rw
          run: |
            uname -a
            cd gradle-it
            rm ./gradlew
            gradle clean build k8sBuild 
