name: Windows Build with Gradle 

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  JKUBE_REPOSITORY: https://github.com/rohanKanojia/jkube.git
  JKUBE_REVISION: pr/buildpacks-build-strategy
  JKUBE_DIR: jkube

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Get Windows Version > Used to retrieve specific Docker Image
        shell: cmd
        run: |
          ver
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Setup Java 17
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout JKube Repository
        run: |
          git config --system core.longpaths true
          git clone $env:JKUBE_REPOSITORY
          cd $env:JKUBE_DIR
          git checkout $env:JKUBE_REVISION
      - name: Install JKube
        run: |
          cd $env:JKUBE_DIR
          mvn -f pom.xml -B -DskipTests clean install
      - name: Install and Run Integration Tests
        run: |
          cd gradle-it
          gradle clean build k8sBuild
